### ISSUE TITLE
Robot visualization

### ISSUE THREAD

**Issue by RonniePonnyTail** [thomas-v2/Web-3D-HMI-Demo#1]
Hi, the PLC side works jsut fine, but i cant see any visualization. If i start http://my-ip:3000/robot.html i only see black screen with header text. Thanks for reply.

**Comment by thomas-v2** [comment]
Hi,
are you using the Internet Explorer (IE11) as browser?
I'm using template strings in the javascript of robot.html, which seems aren't supported by all browsers at the time. I'll see if I can replace them to support other browsers.

**Comment by thomas-v2** [comment]
Checkout the latest version. I've tested it with IE11 which seems to work for me, but the 3D animation in IE11 is much slower than with Firefox on my machine.

**Comment by RonniePonnyTail** [comment]
Hi, thanks for reply. I managed to fix it. Problem was that im using Win10 and npm install use cp to copy libraries into public/js folder so my folder didnt existed becouse win command line do not know cp i guess. So i copied it manualy and its working now, thank oyu

**Comment by thomas-v2** [comment]
I've modified the postinstall script to be OS independant. I've had cygwin installed so I haven't noticed that it doesn't work on Windows without this.
